//*****************************************************************************
//
// Proyecto de microcontroladores SEPA 4º GIERM, Francisco Javier Román Cortés y Juan de Dios Herrera Hurtado.
//
// Copyright (c) 2013-2020 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
// Texas Instruments (TI) is supplying this software for use solely and
// exclusively on TI's microcontroller products. The software is owned by
// TI and/or its suppliers, and is protected under applicable copyright
// laws. You may not combine this software with "viral" open-source
// software in order to form a larger program.
// 
// THIS SOFTWARE IS PROVIDED "AS IS" AND WITH ALL FAULTS.
// NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT
// NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE. TI SHALL NOT, UNDER ANY
// CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL, OR CONSEQUENTIAL
// DAMAGES, FOR ANY REASON WHATSOEVER.
// 
// This is part of revision 2.2.0.295 of the EK-TM4C1294XL Firmware Package.
//
//*****************************************************************************


#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <FT800_TIVA.h>
#include "driverlib2.h"
#include "utils/locator.h"
#include "utils/lwiplib.h"
#include "utils/uartstdio.h"
#include "utils/ustdlib.h"
#include "httpserver_raw/httpd.h"
#include "drivers/pinout.h"
#include "io.h"
#include "cgifuncs.h"
#include <time.h>

//*****************************************************************************
//
//! \addtogroup example_list
//! <h1>Ethernet-based I/O Control (enet_io)</h1>
//!
//! This example application demonstrates web-based I/O control using the
//! Tiva Ethernet controller and the lwIP TCP/IP Stack.  DHCP is used to
//! obtain an Ethernet address.  If DHCP times out without obtaining an
//! address, a static IP address will be chosen using AutoIP.  The address that
//! is selected will be shown on the UART allowing you to access the
//! internal web pages served by the application via your normal web browser.
//!
//! Two different methods of controlling board peripherals via web pages are
//! illustrated via pages labeled ``IO Control Demo 1'' and ``IO Control
//! Demo 2'' in the navigation menu on the left of the application's home page.
//! In both cases, the example allows you to toggle the state of the user LED
//! on the board and set the speed of a blinking LED.
//!
//! ``IO Control Demo 1'' uses JavaScript running in the web browser to send
//! HTTP requests for particular special URLs.  These special URLs are
//! intercepted in the file system support layer (io_fs.c) and used to
//! control the LED and animation LED.  Responses generated by the board are
//! returned to the browser and inserted into the page HTML dynamically by
//! more JavaScript code.
//!
//! ``IO Control Demo 2'' uses standard HTML forms to pass parameters to CGI
//! (Common Gateway Interface) handlers running on the board.  These handlers
//! process the form data and control the animation and LED as requested before
//! sending a response page (in this case, the original form) back to the
//! browser.  The application registers the names and handlers for each of its
//! CGIs with the HTTPD server during initialization and the server calls
//! these handlers after parsing URL parameters each time one of the CGI URLs
//! is requested.
//!
//! Information on the state of the various controls in the second demo is
//! inserted into the served HTML using SSI (Server Side Include) tags which
//! are parsed by the HTTPD server in the application.  As with the CGI
//! handlers, the application registers its list of SSI tags and a handler
//! function with the web server during initialization and this handler is
//! called whenever any registered tag is found in a .shtml, .ssi, .shtm or
//! .xml file being served to the browser.
//!
//! In addition to LED and animation speed control, the second example also
//! allows a line of text to be sent to the board for output to the UART.
//! This is included to illustrate the decoding of HTTP text strings.
//!
//! Note that the web server used by this example has been modified from the
//! example shipped with the basic lwIP package.  Additions include SSI and
//! CGI support along with the ability to have the server automatically insert
//! the HTTP headers rather than having these built in to the files in the
//! file system image.
//!
//! Source files for the internal file system image can be found in the ``fs''
//! directory.  If any of these files are changed, the file system image
//! (io_fsdata.h) should be rebuilt by running the following command from the
//! enet_io directory:
//!
//! ../../../../tools/bin/makefsfile -i fs -o io_fsdata.h -r -h -q
//!
//! For additional details on lwIP, refer to the lwIP web page at:
//! http://savannah.nongnu.org/projects/lwip/
//
//*************************************************************************************************************************************************
// =======================================================================
// Function Declarations
// =======================================================================
#define dword long
#define byte char

volatile int Max_pos = 4200; //Posición izquierda
volatile int Med_pos = 2750; //Posición central
volatile int Min_pos = 1300; //Posición derecha

#define B1_OFF GPIOPinRead(GPIO_PORTJ_BASE,GPIO_PIN_0)
#define B1_ON !(GPIOPinRead(GPIO_PORTJ_BASE,GPIO_PIN_0))
#define B2_OFF GPIOPinRead(GPIO_PORTJ_BASE,GPIO_PIN_1)
#define B2_ON !(GPIOPinRead(GPIO_PORTJ_BASE,GPIO_PIN_1))

#define Boton_borrado_urgente Boton(1*HSIZE/10, 7.5*VSIZE/9, 100, 35, 23, "Borrar")
#define Boton_borrado_no_urgente Boton(6*HSIZE/10, 7.5*VSIZE/9, 100, 35, 23, "Borrar")
#define Boton_volver Boton(HSIZE/20-12, 7*VSIZE/9+14, 63, 28, 23, "Volver")
#define Boton_ver_mensaje Boton(7*HSIZE/10-25, 7*VSIZE/9+14, 115, 28, 23, "Ver mensaje")
#define Boton_enviar_ayuda Boton(3*HSIZE/10-20, 7*VSIZE/9+14, 115, 28, 23, "Enviar ayuda")

#define MSEC 40000

// =======================================================================
// Variable Declarations
// =======================================================================

char chipid = 0;                        // Holds value of Chip ID read from the FT800

unsigned long cmdBufferRd = 0x00000000;         // Store the value read from the REG_CMD_READ register
unsigned long cmdBufferWr = 0x00000000;         // Store the value read from the REG_CMD_WRITE register
unsigned int t=0;
// ############################################################################################################
// User Application - Initialization of MCU / FT800 / Display
// ############################################################################################################


unsigned long POSX, POSY, BufferXY;
unsigned int CMD_Offset = 0;
int32_t REG_TT[6];
const int32_t REG_CAL[6]={22073,59,-1044578,400,-16911,16162095};
const int32_t REG_CAL5[6]={32146, -1428, -331110, -40, -18930, 18321010};


#define NUM_SSI_DATA            3

char mensaje[50];   //Cadenas de caracteres para sacar por pantalla
char cadena_aux[100]; //Cadena auxiliar para pantalla de detalle de datos
int flag = 0;
int registro = 0;
int ver_mensaje_urgente = 0;
int ver_mensaje_no_urgente = 0;
volatile int contador_estado2 = 0;
volatile int contador_borrando = 0;
char hora_alerta[50];
volatile int estado = 0;
volatile int direccion_obtenida = 0;
volatile int horas_aviso = 0, minutos_aviso = 0, segundos_aviso = 0;
volatile int cambio_estado = 0;
volatile int cont_circulos = 0;

volatile int mensajes_urgentes = 0;
volatile int mensajes_no_urgentes = 0;

char cadena_urgente[] = "Mensaje urgente";
char cadena_no_urgente[] = "Mensaje rutinario";
char cadena_tipo_mensaje[50];

volatile char hora_actual[100];

struct StructResumen {
   char  Tipo_mensaje_s[50];
   char  Hora_s[50];
   char  Nombre_s[50];
   char  Apellidos_s[50];
   char  Direccion_s[50];
   char  Edad_s[50];
   char  Telefono_s[50];
   char  Mensaje_s[200];
};

//Array de struct para los 100 avisos urgentes
struct StructResumen RegistroUrgente[20];

//Array de struct para los 100 avisos no urgentes
struct StructResumen RegistroNoUrgente[20];

////Define con el tamaño del array principal
//#define tam_RegistroPantalla    6
//*****************************************************************************
//
// Defines for setting up the system clock.
//
//*****************************************************************************
#define SYSTICKHZ               100
#define SYSTICKMS               (1000 / SYSTICKHZ)

//*****************************************************************************
//
// Interrupt priority definitions.  The top 3 bits of these values are
// significant with lower values indicating higher priority interrupts.
//
//*****************************************************************************
#define SYSTICK_INT_PRIORITY    0x80
#define ETHERNET_INT_PRIORITY   0xC0

//*****************************************************************************
//
// A set of flags.  The flag bits are defined as follows:
//
//     0 -> An indicator that the animation timer interrupt has occurred.
//
//*****************************************************************************
#define FLAG_TICK            0
static volatile unsigned long g_ulFlags;

//*****************************************************************************
//
// External Application references.
//
//*****************************************************************************
extern void httpd_init(void);

//**********************************************************************************
//Lo que se recibe de la página web
//**********************************************************************************
volatile int urgente = 0;           //Valor -1 si no se marca y valor '0' (porque es la primera etiqueta que encuentra) si está marcado
volatile char Nombre[50];
volatile char Apellidos[50];
volatile char Direccion[50];
volatile char Edad[50];
volatile char Telefono[50];
volatile char Mensaje[200];

//*****************************************************************************
//
// Prototypes for the various CGI handler functions.
//
//*****************************************************************************
static char *ControlCGIHandler(int32_t iIndex, int32_t i32NumParams,
                               char *pcParam[], char *pcValue[]);
//static char *SetTextCGIHandler(int32_t iIndex, int32_t i32NumParams,
//                               char *pcParam[], char *pcValue[]);

//*****************************************************************************
//
// CGI URI indices for each entry in the g_psConfigCGIURIs array.
//
//*****************************************************************************
#define CGI_INDEX_CONTROL       0
#define CGI_INDEX_TEXT          1

//*****************************************************************************
//
// This array is passed to the HTTPD server to inform it of special URIs
// that are treated as common gateway interface (CGI) scripts.  Each URI name
// is defined along with a pointer to the function which is to be called to
// process it.
//
//*****************************************************************************
static const tCGI g_psConfigCGIURIs[] =
{
    { "/iocontrol.cgi", (tCGIHandler)ControlCGIHandler }, // CGI_INDEX_CONTROL
//    { "/settxt.cgi", (tCGIHandler)SetTextCGIHandler }     // CGI_INDEX_TEXT
};

//*****************************************************************************
//
// The number of individual CGI URIs that are configured for this system.
//
//*****************************************************************************
#define NUM_CONFIG_CGI_URIS     (sizeof(g_psConfigCGIURIs) / sizeof(tCGI))

//*****************************************************************************
//
// The file sent back to the browser by default following completion of any
// of our CGI handlers.  Each individual handler returns the URI of the page
// to load in response to it being called.
//
//*****************************************************************************
#define DEFAULT_CGI_RESPONSE    "/io_cgi.ssi"

//*****************************************************************************
//
// Timeout for DHCP address request (in seconds).
//
//*****************************************************************************
#ifndef DHCP_EXPIRE_TIMER_SECS
#define DHCP_EXPIRE_TIMER_SECS  45
#endif

//*****************************************************************************
//
// The current IP address.
//
//*****************************************************************************
uint32_t g_ui32IPAddress;

//*****************************************************************************
//
// The system clock frequency.  Used by the SD card driver.
//
//*****************************************************************************
uint32_t g_ui32SysClock;

//*****************************************************************************
//
// The error routine that is called if the driver library encounters an error.
//
//*****************************************************************************
#ifdef DEBUG
void
__error__(char *pcFilename, uint32_t ui32Line)
{
}
#endif

//*****************************************************************************
//
// This CGI handler is called whenever the web browser requests iocontrol.cgi.
//
//*****************************************************************************
static char *
ControlCGIHandler(int32_t iIndex, int32_t i32NumParams,
                  char *pcParam[], char *pcValue[])                     //Entra cuando le damos a "Solicitar atención"
{   long lStringParam;

    urgente = FindCGIParameter("urgente", pcParam, i32NumParams);

    // Si es urgente vale '0' y si no es urgente vale '-1'
    if (urgente == -1) strcpy(cadena_tipo_mensaje, cadena_no_urgente);
    else if (urgente == 0) strcpy(cadena_tipo_mensaje, cadena_urgente);

    lStringParam = FindCGIParameter("nombre", pcParam, i32NumParams);
    DecodeFormString(pcValue[lStringParam], Nombre, 50);

    lStringParam = FindCGIParameter("apellidos", pcParam, i32NumParams);
    DecodeFormString(pcValue[lStringParam], Apellidos, 50);

    lStringParam = FindCGIParameter("direccion", pcParam, i32NumParams);
    DecodeFormString(pcValue[lStringParam], Direccion, 50);

    lStringParam = FindCGIParameter("edad", pcParam, i32NumParams);
    DecodeFormString(pcValue[lStringParam], Edad, 50);

    lStringParam = FindCGIParameter("numerotelefono", pcParam, i32NumParams);
    DecodeFormString(pcValue[lStringParam], Telefono, 50);

    lStringParam = FindCGIParameter("TextoSupervisor", pcParam, i32NumParams);
    DecodeFormString(pcValue[lStringParam], Mensaje, 200);

    if (urgente == 0){       //Si el mensaje es urgente
        strcpy(RegistroUrgente[mensajes_urgentes].Tipo_mensaje_s, cadena_tipo_mensaje);   //Valor -1 si no se marca y valor '0' (porque es la primera etiqueta que encuentra) si está marcado
        strcpy(RegistroUrgente[mensajes_urgentes].Hora_s, hora_actual);
        strcpy(RegistroUrgente[mensajes_urgentes].Nombre_s, Nombre);
        strcpy(RegistroUrgente[mensajes_urgentes].Apellidos_s, Apellidos);
        strcpy(RegistroUrgente[mensajes_urgentes].Direccion_s, Direccion);
        strcpy(RegistroUrgente[mensajes_urgentes].Edad_s, Edad);
        strcpy(RegistroUrgente[mensajes_urgentes].Telefono_s, Telefono);
        strcpy(RegistroUrgente[mensajes_urgentes].Mensaje_s, Mensaje);
        mensajes_urgentes = mensajes_urgentes + 1;
    }
    else{                   //Si el mensaje no es urgente
        strcpy(RegistroNoUrgente[mensajes_no_urgentes].Tipo_mensaje_s, cadena_tipo_mensaje);   //Valor -1 si no se marca y valor '0' (porque es la primera etiqueta que encuentra) si está marcado
        strcpy(RegistroNoUrgente[mensajes_no_urgentes].Hora_s, hora_actual);
        strcpy(RegistroNoUrgente[mensajes_no_urgentes].Nombre_s, Nombre);
        strcpy(RegistroNoUrgente[mensajes_no_urgentes].Apellidos_s, Apellidos);
        strcpy(RegistroNoUrgente[mensajes_no_urgentes].Direccion_s, Direccion);
        strcpy(RegistroNoUrgente[mensajes_no_urgentes].Edad_s, Edad);
        strcpy(RegistroNoUrgente[mensajes_no_urgentes].Telefono_s, Telefono);
        strcpy(RegistroNoUrgente[mensajes_no_urgentes].Mensaje_s, Mensaje);

        mensajes_no_urgentes = mensajes_no_urgentes + 1;
    }

    cambio_estado = 1;

    return(DEFAULT_CGI_RESPONSE);
}

//*****************************************************************************
//
// This CGI handler is called whenever the web browser requests settxt.cgi.
//
//*****************************************************************************
//static char *
//SetTextCGIHandler(int32_t i32Index, int32_t i32NumParams, char *pcParam[],              //Entra cuando metemos un mensaje
//                  char *pcValue[])
//{
//    long lStringParam;
//    char pcDecodedString[48];
//
//    return(DEFAULT_CGI_RESPONSE);
//}

//*****************************************************************************
//
// The interrupt handler for the SysTick interrupt.
//
//*****************************************************************************
void
SysTickIntHandler(void)
{
    //
    // Call the lwIP timer handler.
    //
    lwIPTimer(SYSTICKMS);
}

//*****************************************************************************
//
// Display an lwIP type IP Address.
//
//*****************************************************************************
void
DisplayIPAddress(uint32_t ui32Addr)
{
    char pcBuf[16];

    //
    // Convert the IP Address into a string.
    //
    usprintf(pcBuf, "%d.%d.%d.%d", ui32Addr & 0xff, (ui32Addr >> 8) & 0xff,
            (ui32Addr >> 16) & 0xff, (ui32Addr >> 24) & 0xff);

    //
    // Display the string.
    //
    UARTprintf(pcBuf);
}

//*****************************************************************************
//
// Required by lwIP library to support any host-related timer functions.
//
//*****************************************************************************
void
lwIPHostTimerHandler(void)
{
    uint32_t ui32NewIPAddress;

    //
    // Get the current IP address.
    //
    ui32NewIPAddress = lwIPLocalIPAddrGet();

    //
    // See if the IP address has changed.
    //
    if(ui32NewIPAddress != g_ui32IPAddress)
    {
        //
        // See if there is an IP address assigned.
        //
        if(ui32NewIPAddress == 0xffffffff)
        {
            //
            // Indicate that there is no link.
            //
            UARTprintf("Esperando enlace\n");
        }
        else if(ui32NewIPAddress == 0)
        {
            //
            // There is no IP address, so indicate that the DHCP process is
            // running.
            //
            UARTprintf("Esperando dirección IP\n");
        }
        else
        {
            //
            // Display the new IP address.
            //
            UARTprintf("Dirección IP: ");
            DisplayIPAddress(ui32NewIPAddress);
            UARTprintf("\n");
            UARTprintf("Abra un buscador e inserte la dirección IP\n");
            direccion_obtenida = 1;
        }

        //
        // Save the new IP address.
        //
        g_ui32IPAddress = ui32NewIPAddress;
    }

    //
    // If there is not an IP address.
    //
    if((ui32NewIPAddress == 0) || (ui32NewIPAddress == 0xffffffff))
    {
        //
        // Do nothing and keep waiting.
        //
    }
}

void Funcion_nota(void);
void IntTimer0(void);
void IntTimer1(void);
void Pantalla_inicial(void);
void Pantalla_registro(void);
void Pantalla_alerta1(void);
void Pantalla_alerta2(void);
void Pantalla_borrado(void);
void Pantalla_detalle(void);
void ComProgress(int16_t x,int16_t y,int16_t w,int16_t h,uint16_t options,uint16_t val,uint16_t range);
int map(int valor, int entradaMin, int entradaMax, int salidaMin, int salidaMax);
void MuestraDetalles(int registro, int urgente);
void MuestraMensaje(int registro, int urgente, int no_urgente);

//*****************************************************************************
//
// This example demonstrates the use of the Ethernet Controller and lwIP
// TCP/IP stack to control various peripherals on the board via a web
// browser.
//
//*****************************************************************************
int main(void)
{   int i;
    uint32_t ui32User0, ui32User1;
    uint8_t pui8MACArray[8];

    //
    // Make sure the main oscillator is enabled because this is required by
    // the PHY.  The system must have a 25MHz crystal attached to the OSC
    // pins.  The SYSCTL_MOSC_HIGHFREQ parameter is used when the crystal
    // frequency is 10MHz or higher.
    //
    SysCtlMOSCConfigSet(SYSCTL_MOSC_HIGHFREQ);

    //
    // Run from the PLL at 120 MHz.
    // Note: SYSCTL_CFG_VCO_240 is a new setting provided in TivaWare 2.2.x and
    // later to better reflect the actual VCO speed due to SYSCTL#22.
    //
    g_ui32SysClock = SysCtlClockFreqSet((SYSCTL_XTAL_25MHZ | SYSCTL_OSC_MAIN | SYSCTL_USE_PLL | SYSCTL_CFG_VCO_480), 120000000);

    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Habilitamos puertos
    //
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOA);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPION);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOG);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOJ);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_PWM0);

    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //
    // Configure debug port for internal use.
    //
    //////////////////////////////// UART ///////////////////////////////////////////////////////////////////////////////////////////////////
    SysCtlPeripheralEnable(SYSCTL_PERIPH_UART0);    //Se habilita la UART0
    GPIOPinConfigure(GPIO_PA0_U0RX);                //Pin A0 para recibir
    GPIOPinConfigure(GPIO_PA1_U0TX);                //Pin A1 para enviar
    GPIOPinTypeUART(GPIO_PORTA_BASE, GPIO_PIN_0 | GPIO_PIN_1);  //Pin A0 y A1 para el uso de la UART

    UARTStdioConfig(0, 115200, g_ui32SysClock);  //A 115200 baudios

    //////////////////////////////////////// PWM //////////////////////////////////////////////////////////////////////////
    GPIOPinConfigure(GPIO_PG0_M0PWM4);          //Configurar el pin a PWM
    GPIOPinTypePWM(GPIO_PORTG_BASE, GPIO_PIN_0); //Pin PG0 para PWM

    //////////////////////////////////// CONFIGURACIÓN PANTALLA //////////////////////////////////////////////////////////
    HAL_Init_SPI(1, g_ui32SysClock);  //Boosterpack a usar, Velocidad del MC
    Inicia_pantalla();
    SysCtlDelay(g_ui32SysClock/3);

    #ifdef VM800B50
        for(i=0;i<6;i++)    Esc_Reg(REG_TOUCH_TRANSFORM_A+4*i, REG_CAL5[i]);
    #endif

    /////////////////////////////////////////TIMER 0 PARA LOS 500 MS//////////////////////////////////////////////////////////
    SysCtlPeripheralEnable(SYSCTL_PERIPH_TIMER0); //Se usa el timer 0
    TimerClockSourceSet(TIMER0_BASE, TIMER_CLOCK_SYSTEM); //T0 a 120MHz
    TimerConfigure(TIMER0_BASE, TIMER_CFG_PERIODIC); //T0 de un solo disparo y 32bits
    TimerLoadSet(TIMER0_BASE, TIMER_A, g_ui32SysClock-1); //Se cargan 1 segundo en la cuenta
    TimerIntRegister(TIMER0_BASE,TIMER_A,IntTimer0); //"IntTimer0" nombre de la rutina de interrupción del timer 0
    IntEnable(INT_TIMER0A); //Habilitar la interrupción del timer
    TimerIntEnable(TIMER0_BASE, TIMER_TIMA_TIMEOUT); // ints timeout

    /////////////////////////////////////// TIMER 1 para la hora (tiempo de ejecución del programa) //////////////////////////////////////////////////////////////////////
    SysCtlPeripheralEnable(SYSCTL_PERIPH_TIMER1); //Se usa el timer 1
    TimerClockSourceSet(TIMER1_BASE, TIMER_CLOCK_SYSTEM); //T1 a 120MHz
    TimerConfigure(TIMER1_BASE, TIMER_CFG_PERIODIC); //T1 periódico y 32bits
    TimerLoadSet(TIMER1_BASE, TIMER_A, g_ui32SysClock-1); //Se carga 1 segundo en la cuenta
    TimerIntRegister(TIMER1_BASE,TIMER_A,IntTimer1); //"IntTimer1" nombre de la rutina de interrupción del timer 1
    IntEnable(INT_TIMER1A); //Habilitar la interrupción del timer
    TimerIntEnable(TIMER1_BASE, TIMER_TIMA_TIMEOUT); // ints timeout
    TimerEnable(TIMER1_BASE, TIMER_A); //Habilita Timer1 (empieza a contar)
    IntMasterEnable();                      // Habilitar globalmente las ints

    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //
    // Configure SysTick for a periodic interrupt.
    //
    MAP_SysTickPeriodSet(g_ui32SysClock / SYSTICKHZ);
    MAP_SysTickEnable();
    MAP_SysTickIntEnable();

    //
    // Configure the hardware MAC address for Ethernet Controller filtering of
    // incoming packets.  The MAC address will be stored in the non-volatile
    // USER0 and USER1 registers.
    //
    MAP_FlashUserGet(&ui32User0, &ui32User1);
    if((ui32User0 == 0xffffffff) || (ui32User1 == 0xffffffff))
    {
        //
        // Let the user know there is no MAC address
        //
        UARTprintf("Dirección MAC no programada\n");

        while(1)
        {
        }
    }

    //
    // Tell the user what we are doing just now.
    //
    UARTprintf("Esperando IP\n");

    //
    // Convert the 24/24 split MAC address from NV ram into a 32/16 split
    // MAC address needed to program the hardware registers, then program
    // the MAC address into the Ethernet Controller registers.
    //
    pui8MACArray[0] = ((ui32User0 >>  0) & 0xff);
    pui8MACArray[1] = ((ui32User0 >>  8) & 0xff);
    pui8MACArray[2] = ((ui32User0 >> 16) & 0xff);
    pui8MACArray[3] = ((ui32User1 >>  0) & 0xff);
    pui8MACArray[4] = ((ui32User1 >>  8) & 0xff);
    pui8MACArray[5] = ((ui32User1 >> 16) & 0xff);

    //
    // Initialize the lwIP library, using DHCP.
    //
    lwIPInit(g_ui32SysClock, pui8MACArray, 0, 0, 0, IPADDR_USE_DHCP);

    //
    // Setup the device locator service.
    //
    LocatorInit();
    LocatorMACAddrSet(pui8MACArray);
    LocatorAppTitleSet("EK-TM4C1294XL enet_io");

    //
    // Initialize a sample httpd server.
    //
    httpd_init();

    //
    // Set the interrupt priorities.  We set the SysTick interrupt to a higher
    // priority than the Ethernet interrupt to ensure that the file system
    // tick is processed if SysTick occurs while the Ethernet handler is being
    // processed.  This is very likely since all the TCP/IP and HTTP work is
    // done in the context of the Ethernet interrupt.
    //
    MAP_IntPrioritySet(INT_EMAC0, ETHERNET_INT_PRIORITY);
    MAP_IntPrioritySet(FAULT_SYSTICK, SYSTICK_INT_PRIORITY);

    //
    // Pass our CGI handlers to the HTTP server.
    //
    http_set_cgi_handlers(g_psConfigCGIURIs, NUM_CONFIG_CGI_URIS);

    //
    // Loop forever, processing the on-screen animation.  All other work is
    // done in the interrupt handlers.
    //

    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    while(1){
        switch (estado){
        case 0: //Pantalla de inicio del programa

            Pantalla_detalle();
            MuestraDetalles(registro,1);
            if(Boton_volver) estado = 1;    //Volver a la pantalla de registros
            if(Boton_enviar_ayuda){          //Ir a ver el mensaje (otra pantalla)
                ver_mensaje_urgente = 1;
                estado = 8;
            }
            if(Boton_ver_mensaje){
                estado = 9;
            }
            Dibuja();
        break;
        case 1: //Pantalla de registro con los avisos                                       ¡¡¡¡¡¡¡REVISAR COORDENADA "Y"!!!!!!!
            //                Nueva_pantalla(51,222,204);
            //
            //                ComColor(255,255,255);
            //                ComTXT(7*HSIZE/8, VSIZE/20, 23, OPT_CENTER, hora_actual);
            Pantalla_registro();
            //                Lee_pantalla();
            //
            //                //4 campos de pulsaciones para ver la información de cada uno (PARA URGENTE)
            //                if(POSX>HSIZE/13 && POSX<HSIZE/2 && POSY>3*VSIZE/9 && POSY<4*VSIZE/9){
            //                   registro = 1;
            //                   estado = 6;
            //                }
            //                if(POSX>HSIZE/13 && POSX<HSIZE/2 && POSY>4*VSIZE/9 && POSY<=5*VSIZE/9){
            //                    registro = 2;
            //                    estado = 6;
            //                }
            //                if(POSX>HSIZE/13 && POSX<HSIZE/2 && POSY>5*VSIZE/9 && POSY<=6*VSIZE/9){
            //                    registro = 3;
            //                    estado = 6;
            //                }
            //                if(POSX>HSIZE/13 && POSX<HSIZE/2 && POSY>6*VSIZE/9 && POSY<=7*VSIZE/9){
            //                    registro = 4;
            //                    estado = 6;
            //                }
            //
            //                //4 campos de pulsaciones para ver la información de cada uno (PARA NO URGENTE)
            //                if(POSX>=HSIZE/2 && POSX<HSIZE-23 && POSY>3*VSIZE/9 && POSY<4*VSIZE/9){
            //                   registro = 1;
            //                   estado = 7;
            //                }
            //                if(POSX>=HSIZE/2 && POSX<HSIZE-23 && POSY>4*VSIZE/9 && POSY<=5*VSIZE/9){
            //                    registro = 2;
            //                    estado = 7;
            //                }
            //                if(POSX>=HSIZE/2 && POSX<HSIZE-23 && POSY>5*VSIZE/9 && POSY<=6*VSIZE/9){
            //                    registro = 3;
            //                    estado = 7;
            //                }
            //                if(POSX>=HSIZE/2 && POSX<HSIZE-23 && POSY>6*VSIZE/9 && POSY<=7*VSIZE/9){
            //                    registro = 4;
            //                    estado = 7;
            //                }
            /////////////////////////////////////////////////////
            if (Boton_borrado_urgente){
                estado = 3;
            }

            if (Boton_borrado_no_urgente){
                estado = 4;
            }


            /////////////////////////////////////////////////////
            SysCtlDelay(g_ui32SysClock/3);
            Dibuja();
            if (cambio_estado == 1){
                contador_estado2 = 0;
                estado = 2;
            }
            break;

        case 2: //Pantalla de alerta de mensaje entrante
            TimerEnable(TIMER0_BASE, TIMER_A);
            cambio_estado = 0;
            Funcion_nota();
            if (flag == 0){
                Pantalla_alerta1();
                Dibuja();
            }
            if (flag == 1){
                Pantalla_alerta2();
                Dibuja();
            }
            if (contador_estado2 == 2){
                flag = 0;
                FinNota();
                TimerDisable(TIMER0_BASE, TIMER_A);
                estado = 1;
            }
            break;

        case 3:     //Estado para cuando se pulsa el botón de borrar urgente
            //Desplazar hacia arriba los registros urgentes con su botón de borrado
            for(i = 0; i < mensajes_urgentes - 1; i++){
                strcpy(RegistroUrgente[i].Tipo_mensaje_s, RegistroUrgente[i+1].Tipo_mensaje_s);   // <-
                strcpy(RegistroUrgente[i].Nombre_s,       RegistroUrgente[i+1].Nombre_s);
                strcpy(RegistroUrgente[i].Apellidos_s,    RegistroUrgente[i+1].Apellidos_s);
                strcpy(RegistroUrgente[i].Direccion_s,    RegistroUrgente[i+1].Direccion_s);
                strcpy(RegistroUrgente[i].Mensaje_s,      RegistroUrgente[i+1].Mensaje_s);

                sscanf(RegistroUrgente[i+1].Hora_s,     "%s", RegistroUrgente[i].Hora_s);  // ->
                sscanf(RegistroUrgente[i+1].Edad_s,     "%s", RegistroUrgente[i].Edad_s);
                sscanf(RegistroUrgente[i+1].Telefono_s, "%s", RegistroUrgente[i].Telefono_s);
            }
            mensajes_urgentes = mensajes_urgentes - 1;
            while(Boton_borrado_urgente);
            contador_borrando = 0;
            estado = 5;
            break;

        case 4:     //Estado para cuando se pulsa el botón de borrar no urgente
            //Desplazar hacia arriba los registros urgentes con su botón de borrado
            UARTprintf("Borrando registro no urgente\n");
            for(i = 0; i < mensajes_no_urgentes - 1; i++){
                strcpy(RegistroNoUrgente[i].Tipo_mensaje_s, RegistroNoUrgente[i+1].Tipo_mensaje_s);   // <-
                strcpy(RegistroNoUrgente[i].Nombre_s,       RegistroNoUrgente[i+1].Nombre_s);
                strcpy(RegistroNoUrgente[i].Apellidos_s,    RegistroNoUrgente[i+1].Apellidos_s);
                strcpy(RegistroNoUrgente[i].Direccion_s,    RegistroNoUrgente[i+1].Direccion_s);
                strcpy(RegistroNoUrgente[i].Mensaje_s,      RegistroNoUrgente[i+1].Mensaje_s);

                sscanf(RegistroNoUrgente[i+1].Hora_s,     "%s", RegistroNoUrgente[i].Hora_s);  // ->
                sscanf(RegistroNoUrgente[i+1].Edad_s,     "%s", RegistroNoUrgente[i].Edad_s);
                sscanf(RegistroNoUrgente[i+1].Telefono_s, "%s", RegistroNoUrgente[i].Telefono_s);
            }
            mensajes_no_urgentes = mensajes_no_urgentes - 1;
            while(Boton_borrado_no_urgente);
            contador_borrando = 0;
            estado = 5;
            break;

        case 5: //Pantalla de borrando...
            TimerEnable(TIMER0_BASE, TIMER_A);
            Pantalla_borrado();
            Dibuja();

            if (contador_borrando == 3){
                TimerDisable(TIMER0_BASE, TIMER_A);
                estado = 1;
            }
            break;

        case 6:     //Mostrar detalles de un mensaje urgente
            Pantalla_detalle();
            MuestraDetalles(registro,1);
            if(Boton_volver) estado = 1;    //Volver a la pantalla de registros
            if(Boton_enviar_ayuda){          //Ir a ver el mensaje (otra pantalla)
                ver_mensaje_urgente = 1;
                estado = 8;
            }
            if(Boton_ver_mensaje){
                estado = 9;
            }
            Dibuja();
            break;
        case 7:     //Mostrar detalles de un mensaje no urgente
            Pantalla_detalle();
            MuestraDetalles(registro,0);
            if(Boton_volver) estado = 1;    //Volver a la pantalla de registros
            if(Boton_enviar_ayuda){          //Ir a ver el mensaje (otra pantalla)
                ver_mensaje_no_urgente = 1;
                estado = 8;
            }
            if(Boton_ver_mensaje){
                estado = 9;
            }
            Dibuja();
            break;

        case 8:     //Pantalla de ver mensaje
            Pantalla_detalle();
            MuestraMensaje(1,ver_mensaje_urgente,ver_mensaje_no_urgente);
            if(Boton_volver){
                estado = 1;    //Volver a la pantalla de registros
                ver_mensaje_urgente = 0;
                ver_mensaje_no_urgente = 0;
            }
            Dibuja();
            break;

        case 9:     //Enviando ayuda... (Mover Servo, sonidos etc)
            Dibuja();
            break;
        }
    }
}

void Funcion_nota(){
    VolNota(100);
    TocaNota(S_BEEP, N_SI);
}

void IntTimer0(void) //Al contar 1 segundo una vez se entra en el estado 2
{
   TimerIntClear(TIMER0_BASE, TIMER_TIMA_TIMEOUT); // Borra flag

   contador_estado2 = contador_estado2 + 1;
   contador_borrando = contador_borrando + 1;

   flag = !flag;
}

void IntTimer1(void) //Al contar 1 segundo
{
   TimerIntClear(TIMER1_BASE, TIMER_TIMA_TIMEOUT); // Borra flag

   cont_circulos = cont_circulos + 1;

   if (cont_circulos == 4) cont_circulos = 0;

   time_t tiempo = time(NULL);
   struct tm *tlocal = localtime(&tiempo);
   strftime(hora_actual,128,"%H:%M:%S",tlocal);

   //El micro tiene la hora local de Texas, necesitamos sumarle 7 horas
   if (hora_actual[0] == '0' && hora_actual[1] == '0'){hora_actual[0] = '0'; hora_actual[1] = '7';}
   else if (hora_actual[0] == '0' && hora_actual[1] == '1'){hora_actual[0] = '0'; hora_actual[1] = '8';}
   else if (hora_actual[0] == '0' && hora_actual[1] == '2'){hora_actual[0] = '0'; hora_actual[1] = '9';}
   else if (hora_actual[0] == '0' && hora_actual[1] == '3'){hora_actual[0] = '1'; hora_actual[1] = '0';}
   else if (hora_actual[0] == '0' && hora_actual[1] == '4'){hora_actual[0] = '1'; hora_actual[1] = '1';}
   else if (hora_actual[0] == '0' && hora_actual[1] == '5'){hora_actual[0] = '1'; hora_actual[1] = '2';}
   else if (hora_actual[0] == '0' && hora_actual[1] == '6'){hora_actual[0] = '1'; hora_actual[1] = '3';}
   else if (hora_actual[0] == '0' && hora_actual[1] == '7'){hora_actual[0] = '1'; hora_actual[1] = '4';}
   else if (hora_actual[0] == '0' && hora_actual[1] == '8'){hora_actual[0] = '1'; hora_actual[1] = '5';}
   else if (hora_actual[0] == '0' && hora_actual[1] == '9'){hora_actual[0] = '1'; hora_actual[1] = '6';}
   else if (hora_actual[0] == '1' && hora_actual[1] == '0'){hora_actual[0] = '1'; hora_actual[1] = '7';}
   else if (hora_actual[0] == '1' && hora_actual[1] == '1'){hora_actual[0] = '1'; hora_actual[1] = '8';}
   else if (hora_actual[0] == '1' && hora_actual[1] == '2'){hora_actual[0] = '1'; hora_actual[1] = '9';}
   else if (hora_actual[0] == '1' && hora_actual[1] == '3'){hora_actual[0] = '2'; hora_actual[1] = '0';}
   else if (hora_actual[0] == '1' && hora_actual[1] == '4'){hora_actual[0] = '2'; hora_actual[1] = '1';}
   else if (hora_actual[0] == '1' && hora_actual[1] == '5'){hora_actual[0] = '2'; hora_actual[1] = '2';}
   else if (hora_actual[0] == '1' && hora_actual[1] == '6'){hora_actual[0] = '2'; hora_actual[1] = '3';}
   else if (hora_actual[0] == '1' && hora_actual[1] == '7'){hora_actual[0] = '0'; hora_actual[1] = '0';}
   else if (hora_actual[0] == '1' && hora_actual[1] == '8'){hora_actual[0] = '0'; hora_actual[1] = '1';}
   else if (hora_actual[0] == '1' && hora_actual[1] == '9'){hora_actual[0] = '0'; hora_actual[1] = '2';}
   else if (hora_actual[0] == '2' && hora_actual[1] == '0'){hora_actual[0] = '0'; hora_actual[1] = '3';}
   else if (hora_actual[0] == '2' && hora_actual[1] == '1'){hora_actual[0] = '0'; hora_actual[1] = '4';}
   else if (hora_actual[0] == '2' && hora_actual[1] == '2'){hora_actual[0] = '0'; hora_actual[1] = '5';}
   else if(hora_actual[0] == '2' && hora_actual[1] == '3'){hora_actual[0] = '0'; hora_actual[1] = '6';}
   else {}

}

void Pantalla_inicial(void)
{
    Nueva_pantalla(31,58,208);
    ComColor(255,255,255);
    ComTXT(HSIZE/2, 2, 24, OPT_CENTERX,"Atencion de personas");
    ComTXT(HSIZE/2, 27, 24, OPT_CENTERX,"con necesidades especiales");          //Ancho = 320 || Alto = 240

    ComCirculo(160, 134, 67);

    ComColor(255, 0, 0);
    ComRect(110, 119, 210, 151, true);     // Ancho=100,Alto=40
    ComRect(145, 84, 175, 186, true);

    ComColor(0, 0, 0);
    ComTXT(HSIZE/2-38, VSIZE/2, 24, OPT_CENTERX,"F");
    ComTXT(HSIZE/2+38, VSIZE/2, 24, OPT_CENTERX,"J");
    ComTXT(HSIZE/2, 82, 24, OPT_CENTERX,"J");
    ComTXT(HSIZE/2, 158, 24, OPT_CENTERX,"D");

    ComColor(255, 255, 255);
    ComTXT(HSIZE/2-30, 205, 24, OPT_CENTERX,"Conectando");

    if (cont_circulos == 1) ComCirculo(HSIZE/2+50, 224, 5);
    else if (cont_circulos == 2){
        ComCirculo(HSIZE/2+50, 224, 5);
        ComCirculo(HSIZE/2+65, 224, 5);
    }
    else if (cont_circulos == 3){
        ComCirculo(HSIZE/2+50, 224, 5);
        ComCirculo(HSIZE/2+65, 224, 5);
        ComCirculo(HSIZE/2+80, 224, 5);
    }
    else {}
}

void Pantalla_registro(void)
{
    Nueva_pantalla(51,222,204);

    ComColor(0,0,0);
    ComTXT(7*HSIZE/8, VSIZE/20, 23, OPT_CENTER, hora_actual);
    ComTXT(HSIZE/20, VSIZE/20, 23, OPT_CENTERY, "Registro de mensajes");

    ComColor(255,0,0);
    ComTXT(HSIZE/4+10, VSIZE/6, 23, OPT_CENTERY, "Urgente");        //Ancho = 320 || Alto = 240
//    ComTXT(HSIZE/6-13, VSIZE/4+9, 23, OPT_CENTER, "N");
    ComColor(59,32,103);
    ComTXT(3*HSIZE/9-1, VSIZE/4+9, 23, OPT_CENTER, "Hora de llegada"); //(106,69)

    ComColor(255,255,255);
//    ComTXT(HSIZE/6-13, 2*VSIZE/5+2, 23, OPT_CENTER, "1"); //(59,98)
    ComTXT(3*HSIZE/9-1, 2*VSIZE/5+2, 23, OPT_CENTER, RegistroUrgente[0].Hora_s);
//    ComTXT(HSIZE/6-13, VSIZE/2+5, 23, OPT_CENTER, "2");
    ComTXT(3*HSIZE/9-1, VSIZE/2+5, 23, OPT_CENTER, RegistroUrgente[1].Hora_s);
//    ComTXT(HSIZE/6-13, 4*VSIZE/6-7, 23, OPT_CENTER, "3");
    ComTXT(3*HSIZE/9-1, 4*VSIZE/6-7, 23, OPT_CENTER, RegistroUrgente[2].Hora_s);
//    ComTXT(HSIZE/6-13, 3*VSIZE/4+2, 23, OPT_CENTER, "4");
    ComTXT(3*HSIZE/9-1, 3*VSIZE/4+2, 23, OPT_CENTER, RegistroUrgente[3].Hora_s);

    ComColor(255,197,0);
    ComTXT(3*HSIZE/4-40, VSIZE/6, 23, OPT_CENTERY, "No urgente");
//    ComTXT(HSIZE/2+14, VSIZE/4+9, 23, OPT_CENTER, "N");
    ComColor(59,32,103);
    ComTXT(7*HSIZE/9-6, VSIZE/4+9, 23, OPT_CENTER, "Hora de llegada");

    ComColor(255,255,255);
//    ComTXT(HSIZE/2+14, 2*VSIZE/5+2, 23, OPT_CENTER, "1"); //(59,98)
    ComTXT(7*HSIZE/9-6, 2*VSIZE/5+2, 23, OPT_CENTER, RegistroNoUrgente[0].Hora_s);
//    ComTXT(HSIZE/2+14, VSIZE/2+5, 23, OPT_CENTER, "2");
    ComTXT(7*HSIZE/9-6, VSIZE/2+5, 23, OPT_CENTER, RegistroNoUrgente[1].Hora_s);
//    ComTXT(HSIZE/2+14, 4*VSIZE/6-7, 23, OPT_CENTER, "3");
    ComTXT(7*HSIZE/9-6, 4*VSIZE/6-7, 23, OPT_CENTER, RegistroNoUrgente[2].Hora_s);
//    ComTXT(HSIZE/2+14, 3*VSIZE/4+2, 23, OPT_CENTER, "4");
    ComTXT(7*HSIZE/9-6, 3*VSIZE/4+2, 23, OPT_CENTER, RegistroNoUrgente[3].Hora_s);

//    ComColor(0,0,255);
//    ComRect(HSIZE/13, VSIZE/9, HSIZE-23, 8*VSIZE/10+3, false);  //Rectángulo exterior
//    ComLine(HSIZE/2, VSIZE/9, HSIZE/2, 8*VSIZE/10+3, 1);        //Línea vertical del medio
//    ComRect(HSIZE/13, VSIZE/5+7, HSIZE-23, VSIZE/3+3, false);  //Rectángulo
//    ComRect(HSIZE/13, VSIZE/2-9, HSIZE-23, VSIZE/2+19, false);  //Rectángulo
//    ComRect(HSIZE/13, 7*VSIZE/10-1, HSIZE-23, 8*VSIZE/10+3, false);  //Rectángulo
//    ComRect(HSIZE/6+2, VSIZE/5+7, 4*HSIZE/7+7, 8*VSIZE/10+3, false);  //Rectángulo
}

void Pantalla_alerta1(void)
{
    Nueva_pantalla(255,0,255);
    ComColor(0,0,0);
    ComTXT(HSIZE/2, 25, 25, OPT_CENTERX,"!SOLICITUD DE");
    ComTXT(HSIZE/2, 60, 25, OPT_CENTERX,"AYUDA");
    ComTXT(HSIZE/2, 95, 25, OPT_CENTERX,"ENTRANTE!");
    //sprintf(hora_alerta,"%02d:%02d:%02d",horas_aviso, minutos_aviso, segundos_aviso);          //Guardar estas variables en interrupción que procesa cuando llega un mensaje
//    sscanf(hora_actual,     "%s", hora_alerta);  // ->
    //    ComTXT(HSIZE/2, 145, 25, OPT_CENTERX,hora_alerta);
    ComColor(255,255,255);
    ComCirculo(HSIZE/2-10, 170, 10);
    ComRect(HSIZE/2-20, 190, HSIZE/2, 230, 1);
    ComRect(HSIZE/2+20, 160, HSIZE/2+40, 200, 1);
    ComCirculo(HSIZE/2+30, 220, 10);
}

void Pantalla_alerta2(void)
{
    Nueva_pantalla(57,208,31);
    ComColor(0,0,0);
    ComTXT(HSIZE/2, 25, 25, OPT_CENTERX,"!SOLICITUD DE");
    ComTXT(HSIZE/2, 60, 25, OPT_CENTERX,"AYUDA");
    ComTXT(HSIZE/2, 95, 25, OPT_CENTERX,"ENTRANTE!");
    //sprintf(hora_alerta,"%02d:%02d:%02d",horas_aviso, minutos_aviso, segundos_aviso);          //Guardar estas variables en interrupción que procesa cuando llega un mensaje
//    sscanf(hora_actual,     "%s", hora_alerta);  // ->
//    ComTXT(HSIZE/2, 145, 25, OPT_CENTERX,hora_alerta);
    ComColor(255,255,255);
    ComCirculo(HSIZE/2-10, 170, 10);
    ComRect(HSIZE/2-20, 190, HSIZE/2, 230, 1);
    ComRect(HSIZE/2+20, 160, HSIZE/2+40, 200, 1);
    ComCirculo(HSIZE/2+30, 220, 10);
}

void Pantalla_borrado(void)
{
    Nueva_pantalla(31,58,208);
    ComColor(255, 255, 255);
    ComTXT(HSIZE/2-30, 205, 24, OPT_CENTERX,"Borrando");

    ComCirculo(HSIZE/2+50, 224, 5);
    ComCirculo(HSIZE/2+65, 224, 5);
    ComCirculo(HSIZE/2+80, 224, 5);

    ComProgress(HSIZE/6,VSIZE/2,300,30,OPT_FLAT,map(contador_borrando, 0, 3, 0, 100), 100);    //Barra de progreso de borrando...
}

void Pantalla_detalle(void)
{
    Nueva_pantalla(51,222,204);
    ComColor(255, 255, 255);
    ComTXT(HSIZE/2, VSIZE/9, 24, OPT_CENTER,"Detalles del mensaje");
}

void Pantalla_Mensaje(void)
{
    Nueva_pantalla(51,222,204);
    ComColor(255, 255, 255);
    ComTXT(HSIZE/2, VSIZE/9, 24, OPT_CENTER,"Mensaje adjunto:");
}

void ComProgress(int16_t x,int16_t y,int16_t w,int16_t h,uint16_t options,uint16_t val,uint16_t range)
{
    EscribeRam32(CMD_PROGRESS);
    EscribeRam16(x);
    EscribeRam16(y);
    EscribeRam16(w);            //8 parametros de 16bits, 16 bytes: BIEN
    EscribeRam16(h);            //si fuesen 7 parametros de 16 bits, hay que mandar un ultimo EscribeRam16 con ceros.
    EscribeRam16(options);      //En este caso sí hay que mandarle los ceros al final
    EscribeRam16(val);
    EscribeRam16(range);
    EscribeRam16(0);
}

int map(int valor, int entradaMin, int entradaMax, int salidaMin, int salidaMax)   //Por las características de la progress bar de "borrando..." se puede mapear con enteros
{
    return ((((valor-entradaMin)*(salidaMax-salidaMin))/(entradaMax-entradaMin))+salidaMin);
}

void MuestraDetalles(int registro, int urgente)
{
    if(urgente == 1){
        strcpy(cadena_aux,"Tipo de mensaje: ");
        ComTXT(HSIZE/20, 2*VSIZE/9, 22, OPT_CENTERY, strcat(cadena_aux,RegistroUrgente[registro-1].Tipo_mensaje_s));
        strcpy(cadena_aux,"Hora: ");
        ComTXT(HSIZE/20, 3*VSIZE/9, 22, OPT_CENTERY,strcat(cadena_aux,RegistroUrgente[registro-1].Hora_s));
        strcpy(cadena_aux,"Nombre: ");
        ComTXT(HSIZE/20, 4*VSIZE/9, 22, OPT_CENTERY,strcat(cadena_aux,RegistroUrgente[registro-1].Nombre_s));
        strcpy(cadena_aux,"Apellidos: ");
        ComTXT(HSIZE/20, 5*VSIZE/9, 22, OPT_CENTERY,strcat(cadena_aux,RegistroUrgente[registro-1].Apellidos_s));
        strcpy(cadena_aux,"Direccion: ");
        ComTXT(HSIZE/20, 6*VSIZE/9, 22, OPT_CENTERY,strcat(cadena_aux,RegistroUrgente[registro-1].Direccion_s));
        strcpy(cadena_aux,"Edad: ");
        ComTXT(HSIZE/20, 7*VSIZE/9, 22, OPT_CENTERY,strcat(cadena_aux,RegistroUrgente[registro-1].Edad_s));
        strcpy(cadena_aux,"Telefono: ");
        ComTXT(HSIZE/2, 7*VSIZE/9, 22, OPT_CENTERY,strcat(cadena_aux,RegistroUrgente[registro-1].Telefono_s));

    }
    else{
        strcpy(cadena_aux,"Tipo de mensaje: ");
        ComTXT(HSIZE/20, 2*VSIZE/9, 22, OPT_CENTERY, strcat(cadena_aux,RegistroNoUrgente[registro-1].Tipo_mensaje_s));
        strcpy(cadena_aux,"Hora: ");
        ComTXT(HSIZE/20, 3*VSIZE/9, 22, OPT_CENTERY,strcat(cadena_aux,RegistroNoUrgente[registro-1].Hora_s));
        strcpy(cadena_aux,"Nombre: ");
        ComTXT(HSIZE/20, 4*VSIZE/9, 22, OPT_CENTERY,strcat(cadena_aux,RegistroNoUrgente[registro-1].Nombre_s));
        strcpy(cadena_aux,"Apellidos: ");
        ComTXT(HSIZE/20, 5*VSIZE/9, 22, OPT_CENTERY,strcat(cadena_aux,RegistroNoUrgente[registro-1].Apellidos_s));
        strcpy(cadena_aux,"Direccion: ");
        ComTXT(HSIZE/20, 6*VSIZE/9, 22, OPT_CENTERY,strcat(cadena_aux,RegistroNoUrgente[registro-1].Direccion_s));
        strcpy(cadena_aux,"Edad: ");
        ComTXT(HSIZE/20, 7*VSIZE/9, 22, OPT_CENTERY,strcat(cadena_aux,RegistroNoUrgente[registro-1].Edad_s));
        strcpy(cadena_aux,"Telefono: ");
        ComTXT(HSIZE/2, 7*VSIZE/9, 22, OPT_CENTERY,strcat(cadena_aux,RegistroNoUrgente[registro-1].Telefono_s));
    }
}

void MuestraMensaje(int registro, int urgente, int no_urgente){
    if(urgente){
        ComTXT(HSIZE/2, 3*VSIZE/9, 24, OPT_CENTER,RegistroUrgente[registro-1].Mensaje_s); // Sacar RegistroUrgente[registro-1].Mensaje_s[0 al 20] o lo que quepa, cómo se hace?
        //Según el tamaño del mensaje, segmentar en varias lineas: (strtok()?)
    }
    if(no_urgente){
        ComTXT(HSIZE/2, 3*VSIZE/9, 24, OPT_CENTER,RegistroNoUrgente[registro-1].Mensaje_s);
        //Según el tamaño del mensaje, segmentar en varias lineas:
    }

}

